stages:
  - deploy

deploy-scylla-api:
  stage: deploy
  tags: [oc]
  script:
    - GOOS=linux GOARCH=amd64 go build -o bin/scylla-api cmd/scylla-api/main.go
    - scp bin/scylla-api deployer@172.16.51.118:/home/deployer
    - ssh deployer@172.16.51.118 "mv /home/deployer/scylla-api /opt/scylla-api/bin/ && sudo systemctl restart scylla-api.service"
  only:
    refs:
      - release
    changes:
      - "cmd/scylla-api/main.go"
  environment:
    name: production

deploy-people-hour-analyze:
  stage: deploy
  tags: [oc]
  script:
    - GOOS=linux GOARCH=amd64 go build -o bin/people-hour-analyze cmd/people-hour-analyze/main.go
    - scp bin/people-hour-analyze deployer@172.16.51.118:/opt/analyze/bin
  only:
    refs:
      - release
    changes:
      - "cmd/people-hour-analyze/main.go"
  environment:
    name: production

deploy-ta-store-analyze:
  stage: deploy
  tags: [oc]
  script:
    - GOOS=linux GOARCH=amd64 go build -o bin/ta-store-analyze cmd/ta-store-analyze/main.go
    - scp bin/ta-store-analyze deployer@172.16.51.118:/opt/analyze/bin
  only:
    refs:
      - release
    changes:
      - "cmd/ta-store-analyze/main.go"
  environment:
    name: production

deploy-insert-media-data:
  stage: deploy
  tags: [oc]
  script:
    - GOOS=linux GOARCH=amd64 go build -o bin/insert-media-data cmd/insert-media-data/main.go
    - scp bin/insert-media-data deployer@172.16.51.118:/opt/analyze/bin
  only:
    refs:
      - release
    changes:
      - "cmd/insert-media-data/main.go"
  environment:
    name: production

deploy-prometheus-api:
  stage: deploy
  tags: [oc]
  script:
    - GOOS=linux GOARCH=amd64 go build -o bin/prometheus-api cmd/prometheus-api/main.go
  only:
    refs:
      - release
    changes:
      - "cmd/prometheus-api/main.go"
  environment:
    name: production
