stages:
  - deploy

deploy-scylla-api:
  stage: deploy
  tags: [oc]
  script:
    - GOOS=linux GOARCH=amd64 go build -o bin/scylla-api cmd/scylla-api/main.go
    - scp bin/scylla-api deployer@172.16.51.118:/home/deployer
    - sh deployer@172.16.51.118 "mv /home/deployer/scylla-api /opt/scylla-api/bin"
  only:
    refs:
      - main
    # changes:
    #   - "cmd/scylla-api/main.go"
  environment:
    name: production

deploy-prometheus-api:
  stage: deploy
  tags: [oc]
  script:
    - GOOS=linux GOARCH=amd64 go build -o bin/prometheus-api cmd/prometheus-api/main.go
  only:
    refs:
      - main
    changes:
      - "cmd/prometheus-api/main.go"
  environment:
    name: production

deploy-people-hour-analyze-api:
  stage: deploy
  tags: [oc]
  script:
    - GOOS=linux GOARCH=amd64 go build -o bin/people-hour-analyze cmd/people-hour-analyze/main.go
  only:
    refs:
      - main
    changes:
      - "cmd/people-hour-analyze/main.go"
  environment:
    name: production
