stages:
  - build

build-scylla-api:
  stage: build
  tags: [oc]
  script:
    - GOOS=linux GOARCH=amd64 go build -o bin/scylla-api cmd/scylla-api/main.go
    - ls bin/
  only:
    refs:
      - main
    changes:
      - "cmd/scylla-api/main.go"
  environment:
    name: production
